### ISSUE TITLE
Domain-Management/Creating-an-Addon-Domain/

### ISSUE THREAD

**Issue by psychemedia** [reclaimhosting/docs#1]
Docs on this page are actually docs for the previous step?

**Comment by timmmmyboy** [comment]
I noticed that! I'm not sure if [Mkdocs](http://www.mkdocs.org/) is rendering it improperly or what! Thanks for opening the issue though. I'll see if I can track it down. The document is correct in here as best I can tell but Mkdocs is building it incorrectly.

**Comment by psychemedia** [comment]
Looks like it's the dupe on github?
